sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - jruby-1.7.26
  - jruby-9.1.7.0

before_install:
  - gem install bundler -v 1.13.6

script: bundle && ./run_rspec_with_bundled_libraries.sh
